services:
  app:
    container_name: DocuMatcher
    restart: no
    build:
      context: ./
      dockerfile: Dockerfile
    image: documatcher
    ports:
      - "5000:5000"
    env_file:
      - "app.env"
