services:
  app:
    container_name: DocuMatcher
    restart: no
    build:
      context: ./
      dockerfile: Dockerfile
    image: documatcher
    ports:
      - "8080:80"
    env_file:
      - "deployment/app.env"
