name: "Branch on Issue Assignment"
on:
  issues:
    types: [ assigned ]
    branchName: '${issue.number}-${issue.title[0,64]}'

jobs:
  create_issue_branch_job:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue Branch
        uses: robvanderleek/create-issue-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
